language: ruby
rvm:
- 2.3.1

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
  - gh-pages
  - /pages-(.*)/
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CODECLIMATE_REPO_TOKEN=b86b0613c255d3e33b4319513aa606305efb0d7ad613b1aa2dce85399d189afc

addons:
  code_climate:
    repo_token: b86b0613c255d3e33b4319513aa606305efb0d7ad613b1aa2dce85399d189afc

sudo: false
