title: Club de Niños y Niñas
email: info@cnyn.org
description: La Página oficial del Club de Niños y Niñas del D.F. y Estado de México
baseurl: ""
url: "http://cnyn.org"
twitter_username: cnyndfymex
github_username:  lv

# Build settings
markdown: kramdown
theme: minima

#Continuous integration
exclude: [vendor]
