#Variables
title: Club de Niños y Niñas
email: info@cnyn.org
description: La Página oficial del Club de Niños y Niñas del D.F. y Estado de México
baseurl: ""
url: "http://cnyn.org"
twitter_username: cnyndfymex
github_username:  lv
google_analytics: UA-84147144-1

# Build settings
markdown: kramdown
theme: minima

#Continuous integration
exclude: [vendor]

#Gems
gems:
 - jekyll-coffeescript

#Sass
sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed
