#Variables
title: Club de Niños y Niñas
email: info@cnyn.org
description: La Página oficial del Club de Niños y Niñas del D.F. y Estado de México
baseurl: ""
url: "http://cnyn.org"
twitter_username: cnyndfymex
github_username:  lv
google_analytics: UA-84147144-1

# Build settings
markdown: kramdown
theme: minima

#Continuous integration
exclude: [vendor]

#Gems
gems:
 - jekyll-coffeescript

#Sass
sass:
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets
  style: compressed
